# Generated by Django 4.2.5 on 2023-10-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0003_election_box_number_election_invalid_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="date",
            field=models.DateField(default="2023-05-14"),
        ),
    ]
