# Generated by Django 4.2.5 on 2023-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0004_election_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidates",
            name="date",
            field=models.DateField(default="2023-05-14"),
        ),
    ]
